# Matrix Math and Numpy Refresher

> Deep Learning Nanodegree

---

In [1]:
# === Import === #
import numpy as np

In [6]:
# === Scalars === #
s = np.array(5)
print(s.shape)  # 0 dimensions
# Can be used like a normal scalar
t = s + 23
print(t)
print(type(t))

()
28
<class 'numpy.int64'>


In [10]:
# === Vectors === #
v = np.array([5,4,3,2])
print(v.shape)

y = v[2]
print(y)

y = v[2:]
print(y)

(4,)
3
[3 2]


In [13]:
# === Matrices === #
m = np.array([[5,4,3,2], [2,3,4,5], [3,3,4,4], [5,5,6,6]])
print(m.shape)  # 2 dimensions (4, 4)

print(m[1][2])

(4, 4)
4


In [15]:
# === Tensors === #
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],[[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
t.shape

(3, 3, 2, 1)

In [18]:
# === Changing shapes === #
v = np.array([5,4,3,2])
print(v.shape)  # (4,)
# Reshape into 4x1 matrix
x = v.reshape(1, 4)
print(x.shape)  # (1, 4)

# Slice reshaping syntax
x = v[None, :]
print(x.shape)  # (1, 4)

x = v[:, None]
print(x.shape)  # (4, 1)

(4,)
(1, 4)
(1, 4)
(4, 1)


---

## Scalar math

In [23]:
# === Element-wise operations === #
valist = [5, 4, 3, 2, 1]
vals = np.array(valist) + 5
vals

array([10,  9,  8,  7,  6])

In [24]:
# Other syntax
vals = np.array(valist)
vals += 5
vals

array([10,  9,  8,  7,  6])

In [25]:
# === Element-wise matrix operations === #
a = np.array([[5, 5], [6, 7]])
b = np.array([[2, 3], [4, 5]])
a + b

array([[ 7,  8],
       [10, 12]])

---

## Matrix multiplication

In [30]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8]])

b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]])

print(a.shape, b.shape)

c = np.matmul(a, b)
print(c.shape)
print(c)

(2, 4) (4, 3)
(2, 3)
[[ 70  80  90]
 [158 184 210]]


In [31]:
# Matrix product operator
c = a @ b
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [37]:
# === Transpose === #
m = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]])

print(m)
print()
print(m.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [38]:
# Example use-case of transpose for matrix multiplication
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

print(inputs.shape, weights.shape)

(1, 4) (3, 4)


In [41]:
# Doesn't work to get product as is
inputs @ weights

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [42]:
# Transpose the weights and try again
inputs @ weights.T

array([[-0.01299,  0.00664,  0.13494]])

In [44]:
# Or transpose the inputs
weights @ inputs.T
# The result is the transpose of the other result
# Which to use depends on what output shape is needed

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

In [54]:
def prepare_inputs(inputs):
    arr = np.array(inputs)
    
    # create a 2-dimensional ndarray from the given 1-dimensional list
    arr_2d = arr[None, :]
    input_array = arr_2d
    
    # Find the minimum value in input_array
    # subtract that value from all the elements of input_array
    # Store the result in inputs_minus_min
    inputs_minus_min = input_array - np.min(input_array)

    # Find the maximum value in inputs_minus_min
    # divide all of the values in inputs_minus_min by the maximum value
    # Store the results in inputs_div_max
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max

In [56]:
def multiply_inputs(m1, m2):
    # Check the shapes of the matrices m1 and m2. 
    # m1 and m2 will be ndarray objects.
    # If you have not returned False, then calculate the matrix product
    # of m1 and m2 and return it. Do not use a transpose,
    # but you swap their order if necessary
    if m1.shape[1] == m2.shape[0]:
        return m1 @ m2
    elif m2.shape[1] == m1.shape[0]:
        return m2 @ m1
    else:
        # Return False if the shapes cannot be used for matrix
        # multiplication. You may not use a transpose
        return False

In [57]:
def find_mean(values):
    return sum(values) / len(values)

In [58]:
input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]


In [59]:
print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]


In [60]:
print("Mean == {}".format(find_mean([1,3,4])))

Mean == 2.6666666666666665


In [61]:
print(np.__version__)

1.18.3


In [62]:
np.array([-1, 0, 1]).min()

-1